default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: 127.0.0.1
  port: 3306
  database: app_development
  username: rails
  password: rails

test:
  <<: *default
  host: 127.0.0.1
  database: study_pro_api_test
  username: rails
  password: rails

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    port: <%= ENV.fetch("DB_PORT") { 3306 } %>
    database: <%= ENV["DB_NAME"] %>
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: <%= "#{ENV["DB_NAME"]}_cache" %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= "#{ENV["DB_NAME"]}_queue" %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= "#{ENV["DB_NAME"]}_cable" %>
    migrations_paths: db/cable_migrate